spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: gateway
#wii:
#  ip: 127.0.0.1
#  port: 8060
#  health-check-url: http://localhost:8060/health.json
management:
  endpoint:
    health:
      show-details: always
